#!/usr/bin/env bash
set -e

usage() {
  echo "please specify the drive to prepare for NixOS (e.g., /dev/nvme0n1)";
}

if [[ $# == 1 ]]; then
  drive="$1";
else
  usage;
  exit 1;
fi

echo "preparing drive ${drive} for NixOS"
echo ""
echo "WARNING!"
echo "this script will overwrite everything on ${drive}"
echo "the current partition table on ${drive} is:"
sgdisk --print ${drive}
read -r -p "type ${drive} to confirm and overwrite partitions ~> " confirm
if [[ ! ${confirm} == ${drive} ]]; then exit 1; fi

sgdisk --clear ${drive}
sgdisk --new 1:4096:2048000 --typecode 1:ef00 --change-name 1:EFI ${drive}
sgdisk --new 2:2048001: --typecode 2:8309 --change-name 2:luks ${drive}
sgdisk --print ${drive}
partprobe ${drive}; sleep 2
mkfs.vfat -n EFI /dev/disk/by-partlabel/EFI
cryptsetup -v luksFormat /dev/disk/by-partlabel/luks
cryptsetup open /dev/disk/by-partlabel/luks crypt
mkfs.btrfs -f /dev/mapper/crypt
mount -t btrfs /dev/mapper/crypt /mnt
btrfs subvolume create /mnt/root
btrfs subvolume create /mnt/home
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/persist
btrfs subvolume create /mnt/log
btrfs subvolume create /mnt/swap
btrfs subvolume snapshot -r /mnt/root /mnt/root-blank
umount /mnt
mount -o subvol=root,compress=zstd,noatime /dev/mapper/crypt /mnt
mkdir -p /mnt/boot
mount /dev/disk/by-partlabel/EFI /mnt/boot
mkdir -p /mnt/home
mkdir -p /mnt/nix
mkdir -p /mnt/persist
mkdir -p /mnt/var/log
mount -o subvol=home,compress=zstd,noatime /dev/mapper/crypt /mnt/home
mount -o subvol=nix,compress=zstd,noatime /dev/mapper/crypt /mnt/nix
mount -o subvol=persist,compress=zstd,noatime /dev/mapper/crypt /mnt/persist
mount -o subvol=log,compress=zstd,noatime /dev/mapper/crypt /mnt/var/log
mkdir -p /mnt/etc/nixos

echo "prepared ${drive} for NixOS"
echo "your next step is  to install your system from a flake, e.g.:"
echo "  time nixos-install --flake .#encom --no-root-password"
echo "or"
echo "  nixos-install --flake github:bluesquall/tabula-rasa/agenix#encom"

echo ""
echo "afterward, you need to manually install the ssh keys used by agenix,"
echo "or, re-key the secrets to the ssh keys of the new system."
